### PR TITLE
Add support for tracking FXPool

### PR DESCRIPTION
**Pull request by schystz**
https://thegraph.com/hosted-service/subgraph/xave-finance/balancer-v2-polygon?version=pending

### CODE REVIEW

**Comment by markusbkoch** [comment]
Thanks @schystz . Has this been deployed to a subgraph of your own that we can use to verify? Let us know when this is ready for review.

**Comment by schystz** [comment]
Hi @markusbkoch , yes we did create a subgraph here: https://thegraph.com/hosted-service/subgraph/xave-finance/balancer-v2-polygon. It took some time to index, and I only noticed now that there is an error:

> Subgraph failed with non-deterministic error: failed to process trigger: block #32054797 (0xb1d6…3c26), transaction dd38b3773b5c67fea221fca15702b9b54c77afb6f5665d45adc97ccbd03ade99: Could not find ABI for contract "WeightedPool", try adding it to the 'abis' section of the subgraph manifest wasm backtrace: 0: 0x206b - <unknown>!~lib/@graphprotocol/graph-ts/chain/ethereum/ethereum.SmartContract#tryCall 1: 0x44ee - <unknown>!src/mappings/helpers/misc/createToken 2: 0x4a0c - <unknown>!src/mappings/helpers/misc/createPoolTokenEntity 3: 0x4dc1 - <unknown>!src/mappings/poolFactory/handleNewPoolTokens 4: 0x6415 - <unknown>!src/mappings/poolFactory/handleNewFXPool , retry_delay_s: 1800, attempt: 146

It doesn't seem to be related to the changes we made, any ideas on this error?

**Comment by schystz** [comment]
Redeployed the subgraph with the fix [here](https://github.com/balancer-labs/balancer-subgraph-v2/pull/258/commits/cc4b754e51fddcceff658a4da6a6e5bb22ab3bc1). Just waiting again for the sync to finished so we can verify the fix.

**Comment by markusbkoch** [comment]
Hey @schystz a full sync can take a long time on Polygon. You might want to consider grafting, or even better just comment out all data sources other than the vault and your pool factory and set the start block of the vault to be the same as your pool factory's - you'll end up with a much leaner subgraph that only checks that your handler works correctly, but it will sync in no time. @mendesfabio can correct me if I'm wrong and provide the details of how to do that if you need help.

**Comment by schystz** [comment]
Hi @markusbkoch, thanks for the tip! We have updated this PR (resync'ed from `dev` branch as well) and we are now able to query the FX pools from our subgraph clone [here](https://thegraph.com/hosted-service/subgraph/xave-finance/balancer-v2-polygon). However `totalLiquidity` and `totalSwapVolume` remains `0`, even though `totalShares` is about `~1.2M` already and `swapsCount` is at `121`. Any ideas?

**Comment by markusbkoch** [comment]
Hey @schystz glad to see you managed to deploy and sync a stripped down version of the subgraph for the tests.
We recently introduced a change that we still need to better document: the [assets.ts](https://github.com/balancer-labs/balancer-subgraph-v2/blob/master/src/mappings/helpers/assets.ts) file is auto-generated and you might have deployed the polygon subgraph using mainnet information of stable assets and pricing assets. Based on what I'm seeing in your subgraph, that would be my first guess. Could you please try updating assets.ts and redeploying?

**Comment by mendesfabio** [comment]
@schystz Markus is right. I thought that could be the issue and deployed a Subgraph last night for testing. `totalLiquidity` and `totalSwapVolume` are both working here https://thegraph.com/hosted-service/subgraph/mendesfabio/balancer-polygon-v2

FYI to update the `assets.ts` file you'd need to run `yarn generate-assets polygon`

**Comment by schystz** [comment]
Awesome!!! We got it working now after following @mendesfabio advice to run the `generate-assets` cmd first before deploying. Thanks for the much needed help @markusbkoch @mendesfabio!

Marking this as Ready for review now that everything is looking good from our end.

**Comment by markusbkoch** [comment]
Thanks @schystz . Unfortunately a recent update in graph-node prevents the deployment of grafted subgraphs that add data sources to the manifest. We'll have to wait until [this](https://github.com/graphprotocol/graph-node/pull/3989) is merged or merge this PR with the next full sync.

**Comment by leoyvens** [comment]
The issue should be fixed on graph node hosted, please attempt the graft again and let us know if it succeeded.

**Comment by schystz** [comment]
Hi @markusbkoch , I've synced this branch to `dev` and was able to successfully redeployed to our subgraph on https://thegraph.com/hosted-service/subgraph/xave-finance/balancer-v2-polygon. I had to change the `polygon.graft.base` though to our latest deployment ID (locally) before deploying otherwise graph will say graft base is invalid. Seems to work fine on our end.

**Comment by markusbkoch** [comment]
This is now [in production](https://api.thegraph.com/subgraphs/name/balancer-labs/balancer-polygon-v2/graphql?query=%7B%0A++pools%28where%3A%7B%0A++++poolType%3A%22FX%22%0A++%7D%29%7B%0A++++id%0A++%7D%0A%7D), @schystz . Thank you!

**Pull request merged**
